### ISSUE TITLE
Practica #5 Documentacion del sistema

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/documento-de-arquitectura-mitte#2]
[DRS.pdf](https://github.com/SistemasTecTlaxiaco/documento-de-arquitectura-mitte/files/6361878/DRS.pdf)

**Comment by Nancy2050** [comment]
Excelente. 
Puntaje: 20%

**Comment by josealfredo79** [comment]
es DRA no drs

**Comment by josealfredo79** [comment]
Esta bien hecho....
